'use strict';

const DEBUG = false;

const CONFIG_FILENAME = 'zxconf.json';

const UNLOCK_ACCOUNT_PERIOD = 900;

const BLOCK_SIZE = 64;

const TRUFFLE_CONTRACTS_LOCATION = '../truffle-contracts/build/contracts';

const STORAGE_CLIENT_UPLOADS_LOCATION = './uploads/client';

const STORAGE_PROVIDER_UPLOADS_LOCATION = './uploads/provider';

const AGENT_DB = './agent-db.json';

const GAS = 55000000;

const GAS_PRICE = 10;

const HOST = '127.0.0.1';

const PORT = 9870;

const SERVER_MODE = {
  DAEMON: 0,
  STANDALONE: 1,
};

const USE_TRUFFLE_CONTRACTS = false;


// Contract binaries.

const STORAGE_CONTRACT_ABI = './build/StorageAgreement.abi';

const STORAGE_CONTRACT_BIN = './build/StorageAgreement.bin';

const CLOUDAGORA_REGISTRY_ABI = './build/UsersRegistry.abi';

const CLOUDAGORA_REGISTRY_BIN = './build/UsersRegistry.bin';

const CLOUDAGORA_AUCTIONFACTORY_ABI = './build/AuctionFactory.abi';

const CLOUDAGORA_AUCTIONFACTORY_BIN = './build/AuctionFactory.bin';

const CLOUDAGORA_AUCTION_ABI = './build/Auction.abi';

const CLOUDAGORA_AUCTION_BIN = './build/Auction.bin';

const CLOUDAGORA_CONTRACTSREGISTRY_ABI = './build/ContractsRegistry.abi';

const CLOUDAGORA_CONTRACTSREGISTRY_BIN = './build/ContractsRegistry.bin';

const COMPUTE_CONTRACT_ABI = './build/ComputeAgreement.abi';

const COMPUTE_CONTRACT_BIN = './build/ComputeAgreement.bin';


module.exports = {
  GAS: GAS,
  HOST: HOST,
  PORT: PORT,
  DEBUG: DEBUG,
  AGENT_DB: AGENT_DB,
  GAS_PRICE: GAS_PRICE,
  BLOCK_SIZE: BLOCK_SIZE,
  SERVER_MODE: SERVER_MODE,
  CONFIG_FILENAME: CONFIG_FILENAME,
  STORAGE_CONTRACT_ABI: STORAGE_CONTRACT_ABI,
  STORAGE_CONTRACT_BIN: STORAGE_CONTRACT_BIN,
  COMPUTE_CONTRACT_ABI: COMPUTE_CONTRACT_ABI,
  COMPUTE_CONTRACT_BIN: COMPUTE_CONTRACT_BIN,
  USE_TRUFFLE_CONTRACTS: USE_TRUFFLE_CONTRACTS,
  UNLOCK_ACCOUNT_PERIOD: UNLOCK_ACCOUNT_PERIOD,
  CLOUDAGORA_REGISTRY_ABI: CLOUDAGORA_REGISTRY_ABI,
  CLOUDAGORA_REGISTRY_BIN: CLOUDAGORA_REGISTRY_BIN,
  TRUFFLE_CONTRACTS_LOCATION: TRUFFLE_CONTRACTS_LOCATION,
  STORAGE_CLIENT_UPLOADS_LOCATION: STORAGE_CLIENT_UPLOADS_LOCATION,
  STORAGE_PROVIDER_UPLOADS_LOCATION: STORAGE_PROVIDER_UPLOADS_LOCATION,
  CLOUDAGORA_AUCTIONFACTORY_BIN: CLOUDAGORA_AUCTIONFACTORY_BIN,
  CLOUDAGORA_AUCTIONFACTORY_ABI: CLOUDAGORA_AUCTIONFACTORY_ABI,
  CLOUDAGORA_CONTRACTSREGISTRY_BIN: CLOUDAGORA_CONTRACTSREGISTRY_BIN,
  CLOUDAGORA_CONTRACTSREGISTRY_ABI: CLOUDAGORA_CONTRACTSREGISTRY_ABI,
  CLOUDAGORA_AUCTION_ABI: CLOUDAGORA_AUCTION_ABI,
  CLOUDAGORA_AUCTION_BIN: CLOUDAGORA_AUCTION_BIN,
};
